POST http://127.0.0.1:8000/api/users/login/ 
Content-Type: application/json

{ "username": "adam", "password": "Pass1234!"}

###

POST http://127.0.0.1:8000/api/users/signup/ 
Content-Type: application/json

{ "username": "adam", "password": "Pass1234!" }

###

POST http://127.0.0.1:8000/api/courses/
Content-Type: application/json

{ "name": "eslam1", "professor_name": "fazli", "token": "5889d5decd1582f5d87ab2a9882b4c4c87b996dc" }
