# Generated by Django 4.2.4 on 2024-02-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_selected_for_assignment',
            field=models.BooleanField(default=True),
        ),
    ]
