# Generated by Django 5.0.4 on 2024-04-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brainstorming", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brainstorm",
            name="lang",
            field=models.CharField(
                choices=[("Persian", "fa"), ("English", "en")],
                default="en",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
