# Generated by Django 5.0.4 on 2024-04-08 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brainstorming", "0002_brainstorm_lang"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brainstorm",
            name="lang",
            field=models.CharField(
                choices=[("fa", "Persian"), ("en", "English")], max_length=20
            ),
        ),
    ]
