# Generated by Django 4.2.4 on 2024-02-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('role', models.CharField(choices=[('TA', 'Teaching Assistant'), ('HeadTA', 'Head Teaching Assistant'), ('Professor', 'Professor')], max_length=20)),
                ('courses', models.ManyToManyField(related_name='users', to='user.course')),
            ],
        ),
    ]
