# Generated by Django 4.2.4 on 2024-02-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='professor_name',
            field=models.CharField(default='Nan', max_length=100),
            preserve_default=False,
        ),
    ]
