# Generated by Django 5.0.3 on 2024-03-15 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("Theoretical", "Theoretical"),
                            ("Practical", "Practical"),
                            ("Project", "Project"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.course"
                    ),
                ),
            ],
        ),
    ]
