# Generated by Django 5.0.4 on 2024-04-07 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("course", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("Theoretical", "Theoretical"),
                            ("Practical", "Practical"),
                            ("Project", "Project"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="course.course",
                    ),
                ),
            ],
        ),
    ]
