# Generated by Django 4.2.4 on 2024-02-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('Theoretical', 'Theoretical'), ('Practical', 'Practical'), ('Project', 'Project')], max_length=20),
        ),
    ]
